apiVersion: v1
kind: Pod
metadata:
  name: nginx-web01
  labels:
    app: http-app
spec:
  containers:
    - name: nginx-web01
      image: nginx:latest
      ports:
        - name: http-port
          containerPort: 80
      volumeMounts:
        - name: documentroot
          mountPath: /usr/share/nginx/html
  volumes:
    - name: documentroot
      hostPath:
        path: /Users/kinjoyuji/workspace/k8s-hanson/adachisan-hands-on/html
